volumes:
  data:


services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: go-language
